const BEST = [
  { name: "Lechona", origin: "Colombia", emoji: "🐖", category: "Main", tag: "TasteAtlas #1 best dish 2025",
    why: "The actual #1 dish in the world on TasteAtlas's 2025 list of 100 best dishes. A whole pig roasted for hours, stuffed with rice, peas, and spices until the skin turns to crackling and the meat falls apart. It is Colombia's celebration centerpiece — served at weddings and festivals — and voters put it above every other dish on Earth." },
  { name: "Pizza Napoletana", origin: "Naples, Italy", emoji: "🍕", category: "Main", tag: "TasteAtlas #2 · UNESCO heritage",
    why: "Ranked #2 in the world, and the art of the Neapolitan pizzaiolo is UNESCO intangible heritage. Leopard-spotted crust from a 450°C wood oven, San Marzano tomatoes, fior di latte, basil — a formula from 1889 so perfect it colonized the planet. The benchmark every pizza is judged against." },
  { name: "Picanha", origin: "Brazil", emoji: "🥩", category: "Main", tag: "TasteAtlas #3",
    why: "The crown of Brazilian churrasco: a cap of beef with a thick fat layer, seasoned with nothing but coarse salt and grilled over charcoal. Sliced thin against the grain, it is juicy, beefy, and elemental. Brazil's barbecue culture turned one humble cut into the #3 dish on the planet." },
  { name: "Rechta", origin: "Algeria", emoji: "🍝", category: "Main", tag: "TasteAtlas #4",
    why: "Hand-rolled noodles cut into thin artisanal strips, steamed and served in a fragrant spiced broth with chicken or lamb. Algeria's celebratory dish — traditionally made for Eid and weddings — beat nearly every famous dish in Europe and Asia to land at #4. Comfort food with ceremony." },
  { name: "Phanaeng Curry", origin: "Thailand", emoji: "🍛", category: "Main", tag: "TasteAtlas #5",
    why: "A thick, rich red curry simmered down with coconut cream until it glistens, loaded with peanuts, makrut lime, and chilies. Drier and more intense than other Thai curries, it balances sweet, salty, and heat in a single spoonful. Thailand's curry masterpiece, ranked #5 on Earth." },
  { name: "Asado", origin: "Argentina", emoji: "🔥", category: "Main", tag: "TasteAtlas #6",
    why: "Not just a dish but a ritual: beef, pork, chorizo, and morcilla slow-cooked over wood or charcoal by an asador, often for an entire afternoon. The smoke, the patience, the gathering of family around the parrilla — Argentina turned grilling into a national philosophy and the #6 dish in the world." },
  { name: "Çökertme Kebabı", origin: "Bodrum, Turkey", emoji: "🍖", category: "Main", tag: "TasteAtlas #7",
    why: "Strips of marinated veal layered over matchstick fried potatoes, drowned in garlic yogurt and sizzling tomato-butter sauce. Named after a Bodrum folk song, it hits every craving at once — crispy, creamy, meaty, tangy. Turkey's most complete plate, ranked #7 globally." },
  { name: "Rawon", origin: "East Java, Indonesia", emoji: "🍲", category: "Soup", tag: "TasteAtlas #8",
    why: "A beef soup turned nearly black by keluak nuts, giving it a deep, earthy, almost chocolate-like depth you will not find in any other broth. Served with rice, bean sprouts, and salted egg, rawon is Indonesia's dark horse — mysterious-looking, unforgettable-tasting, and the #8 dish in the world." },
  { name: "Cağ Kebabı", origin: "Erzurum, Turkey", emoji: "🍢", category: "Main", tag: "TasteAtlas #9 · #5 in 2026",
    why: "Marinated lamb stacked with tail fat and roasted horizontally over open wood fire in Turkey's high-altitude east. Sheep raised on wild mountain herbs flavor the meat from the inside out. It ranked #9 in 2025 and climbed to #5 best dish in the world for 2026 — the kebab that outranks all kebabs." },
  { name: "Tibs", origin: "Ethiopia", emoji: "🥘", category: "Main", tag: "TasteAtlas #10",
    why: "Chopped beef or lamb seared at ferocious heat with berbere spice, garlic, and niter kibbeh (spiced clarified butter), served sizzling on injera flatbread. Ethiopia's beloved stir-fry is fiery, buttery, and eaten communally — a top-10 dish that turns dinner into a shared event." },
  { name: "Biang Biang Noodles", origin: "Shaanxi, China", emoji: "🍜", category: "Main", tag: "TasteAtlas #11",
    why: "Hand-pulled noodles as wide as belts, slapped and stretched to order, then hit with searing-hot chili oil poured over garlic and vinegar. The name mimics the slap of dough on the counter. Chewy, spicy, dramatic — China's noodle theater, ranked #11 in the world." },
  { name: "Cochinita Pibil", origin: "Yucatán, Mexico", emoji: "🐷", category: "Main", tag: "TasteAtlas #12",
    why: "Pork marinated in sour orange and achiote, wrapped in banana leaves, and slow-roasted in a pit until it surrenders. A Maya technique older than Mexico itself, finished with pickled red onions. The #12 dish on Earth tastes like history you can shred with a fork." },
  { name: "Châteaubriand", origin: "France", emoji: "🥩", category: "Main", tag: "TasteAtlas #13",
    why: "The thick center cut of beef tenderloin, roasted whole and carved tableside, served with béarnaise. Named for a 19th-century French viscount, it is the old-school definition of fine dining — pure, buttery tenderness with zero distractions. France's steak royalty at #13." },
  { name: "Pernil", origin: "Puerto Rico", emoji: "🍖", category: "Main", tag: "TasteAtlas #14",
    why: "A whole pork shoulder marinated in garlic, pepper, and adobo, roasted low and slow until the skin becomes a sheet of crackling called cuerito. The centerpiece of Puerto Rican Christmas — and the reason the island's holiday season smells incredible. Ranked #14 in the world." },
  { name: "Unadon", origin: "Japan", emoji: "🍱", category: "Seafood", tag: "TasteAtlas #15",
    why: "Grilled freshwater eel glazed in sweet-savory tare, laid over steaming rice so the sauce seeps into every grain. Eel is grilled over charcoal in a technique refined over centuries. Rich, lacquered, and deeply umami — Japan's #15 dish is luxury in a lacquered box." },
  { name: "Païdakia", origin: "Greece", emoji: "🍖", category: "Main", tag: "TasteAtlas #16",
    why: "Grilled lamb chops — the rib cut Greeks call the tastiest part of the animal — seasoned with lemon, oregano, and olive oil over charcoal. Simple, smoky, and eaten with your hands at tavernas across Greece. Proof that three ingredients, done right, beat thirty." },
  { name: "Khao Soi", origin: "Chiang Mai, Thailand", emoji: "🍜", category: "Soup", tag: "TasteAtlas #17",
    why: "A coconut-curry noodle soup crowned with a tangle of crispy fried noodles for crunch. Rich, fragrant, and finished with pickled mustard greens, lime, and chili oil at the table. Northern Thailand's signature bowl — two textures of noodle in one dish — ranked #17 on Earth." },
  { name: "Amêijoas à Bulhão Pato", origin: "Portugal", emoji: "🦪", category: "Seafood", tag: "TasteAtlas #18",
    why: "Clams steamed open in white wine with mountains of garlic and fresh coriander, mopped up with crusty bread. Named for a 19th-century Portuguese poet, it is the Algarve's essential appetizer — briny, garlicky, and gone in minutes. Portugal's seafood soul at #18." },
  { name: "Mechouia Salad", origin: "Tunisia", emoji: "🥗", category: "Side", tag: "TasteAtlas #19",
    why: "Peppers and tomatoes charred directly over flame until blackened, then chopped with garlic, olive oil, and sometimes tuna and egg. Smoky, sweet, and bright all at once — Tunisia's grilled salad turns humble vegetables into something voters ranked #19 in the world." },
  { name: "Chakhchoukha", origin: "Algeria", emoji: "🥘", category: "Main", tag: "TasteAtlas #20",
    why: "Torn pieces of flatbread simmered in a spicy tomato-and-meat stew until they drink up every drop. A resourceful desert dish that wastes nothing and tastes like everything — Algeria's second entry in the global top 20, and a masterclass in turning bread into the main event." },
  { name: "Cordero Asado", origin: "Castile, Spain", emoji: "🐑", category: "Main", tag: "TasteAtlas #21",
    why: "Milk-fed lamb roasted in a wood-fired clay oven with nothing but water and salt until the meat collapses and the skin crisps. In Segovia it is carved with the edge of a plate to prove its tenderness. Spain's roast-lamb tradition, ranked #21 in the world." },
  { name: "Weihnachtsgans", origin: "Germany", emoji: "🪿", category: "Main", tag: "TasteAtlas #22",
    why: "The Christmas roast goose: crisp golden skin, rich dark meat, served with red cabbage, dumplings, and chestnut stuffing. Germans have roasted it for the holidays since the Middle Ages. One meal a year — but voters say it is worth the wait, ranking it #22 globally." },
  { name: "Pempek", origin: "Palembang, Indonesia", emoji: "🐟", category: "Street Food", tag: "TasteAtlas #23",
    why: "Fish and tapioca cakes — boiled, then fried — served in a dark, sour-spicy cuko sauce of palm sugar, tamarind, and chili. Palembang's 400-year-old street food is chewy, tangy, and fiery. Indonesia's snack game, ranked #23 on the planet." },
  { name: "Tagliatelle al Ragù", origin: "Bologna, Italy", emoji: "🍝", category: "Main", tag: "TasteAtlas #24",
    why: "The real 'Bolognese': wide ribbons of egg pasta tossed with a slow-simmered ragù of beef, pork, soffritto, wine, and milk — no spaghetti in sight. Bologna's chamber of commerce literally registered the official recipe. Italy's pasta canon, ranked #24." },
  { name: "Tonkotsu Ramen", origin: "Fukuoka, Japan", emoji: "🍥", category: "Soup", tag: "TasteAtlas #25",
    why: "Pork bones boiled at a rolling boil for 12–18 hours until the broth turns milky-white and collagen-thick, paired with thin noodles, chashu, and black garlic oil. Born in Fukuoka's yatai stalls, it is the richest bowl in ramen culture — #25 in the world." },
  { name: "İskender Kebap", origin: "Bursa, Turkey", emoji: "🥙", category: "Main", tag: "TasteAtlas #26",
    why: "Invented in 1867 by İskender Efendi: thin döner slices laid over buttered pita, flooded with tomato sauce, and finished with sizzling browned butter and cool yogurt. Hot, cold, crispy, creamy in every bite — Turkey's 19th-century invention still ranks #26 globally." },
  { name: "Pappardelle al Cinghiale", origin: "Tuscany, Italy", emoji: "🍝", category: "Main", tag: "TasteAtlas #27",
    why: "Wide pappardelle ribbons in a slow-braised wild boar ragù with juniper, red wine, and rosemary. Tuscany's hunters turned game meat into the most rustic, soulful pasta sauce in Italy. Deep, dark, and ranked #27 on Earth." },
  { name: "Kuzu Şiş", origin: "Turkey", emoji: "🍢", category: "Main", tag: "TasteAtlas #28",
    why: "Cubes of lamb marinated in onion, milk, and spices, grilled over charcoal until charred outside and pink inside. Served with sumac onions and flatbread, it is the skewer all other skewers are measured against — #28 in the world." },
  { name: "Murgh Makhani (Butter Chicken)", origin: "Delhi, India", emoji: "🍗", category: "Main", tag: "TasteAtlas #29",
    why: "Invented in 1950s Delhi at Moti Mahal: tandoor-charred chicken folded into a silky tomato-butter-fenugreek sauce. The dish that introduced Indian food to the planet, and still the gateway curry for millions. Ranked #29 among all dishes in the world." },
  { name: "Hyderabadi Biryani", origin: "Hyderabad, India", emoji: "🍚", category: "Main", tag: "TasteAtlas #31",
    why: "Raw marinated meat layered with fragrant basmati, sealed with dough, and steam-cooked (dum) so every grain absorbs saffron, fried onions, and mint. The Nizams' royal kitchens created it; Hyderabad's biryani houses perfected it. India's celebration rice, ranked #31 globally." },
  { name: "Seco de Cabrito", origin: "Peru", emoji: "🍲", category: "Main", tag: "TasteAtlas #1 best stew",
    why: "Topped TasteAtlas's ranking of the world's best stews. Goat slow-braised in cilantro and chicha de jora until meltingly tender — Peru's north-coast celebration dish, and proof that the humblest meat becomes royalty with time and patience." },
  { name: "Hünkar Beğendi", origin: "Turkey", emoji: "🍆", category: "Main", tag: "TasteAtlas #3 best stew",
    why: "Ranked the 3rd best stew in the world. 'The sultan approved' — lamb stew over smoked eggplant purée enriched with cheese, born in the Ottoman palace kitchens. Imperial comfort food that has survived six centuries." },
  { name: "Lasagne alla Bolognese", origin: "Bologna, Italy", emoji: "🍝", category: "Main", tag: "TasteAtlas #35",
    why: "Ranked #35 among the world's best dishes. Layers of fresh egg pasta, slow ragù, béchamel, and Parmigiano baked until bronzed — Bologna's edible architecture, and the Sunday dish that defined Italian dreams worldwide." },
  { name: "Karē", origin: "Japan", emoji: "🍛", category: "Main", tag: "TasteAtlas #36",
    why: "Ranked #36 in the world. Japan's beloved curry rice — a Meiji-era naval import reinvented with dashi depth and served with pickles. Sweet, mild, and eaten weekly by millions; Japan's true national comfort food." },
  { name: "Pollo a la Brasa", origin: "Peru", emoji: "🍗", category: "Main", tag: "TasteAtlas #37",
    why: "Ranked #37 globally. Chicken marinated in ají panca and spices, spit-roasted over open flame until the skin crackles, served with fries and ají sauces. Lima's rotisserie obsession — Peruvians debate the best pollería the way others debate football." },
  { name: "Parmigiana alla Napoletana", origin: "Naples, Italy", emoji: "🍆", category: "Main", tag: "TasteAtlas #38",
    why: "Ranked #38 in the world. Fried eggplant layered with tomato, basil, mozzarella, and Parmigiano, baked until bubbling — Naples' vegetarian masterpiece and southern Italian soul food at its finest." },
  { name: "Texas Brisket", origin: "Texas, USA", emoji: "🥩", category: "Main", tag: "TasteAtlas #42",
    why: "Central Texas-style barbecue ranked #42 among the world's best dishes. A whole brisket smoked low and slow over post oak for 12+ hours until the bark is black and the meat jiggles. Salt, pepper, smoke, patience — nothing else needed." },
  { name: "Gulai", origin: "Indonesia", emoji: "🍛", category: "Main", tag: "TasteAtlas #44",
    why: "Ranked #44 in the world. Indonesia's golden curry — coconut milk simmered with turmeric, lemongrass, and galangal around beef, goat, or fish head. The archipelago's spice-trade heritage in a bowl." },
  { name: "Spaghetti alla Carbonara", origin: "Rome, Italy", emoji: "🍝", category: "Main", tag: "TasteAtlas #45",
    why: "Ranked #45 globally. Rome's holy trinity of guanciale, Pecorino Romano, and egg — no cream, ever — tossed with spaghetti off the heat into silk. Five ingredients, zero forgiveness, infinite reward." },
  { name: "Khachapuri", origin: "Georgia", emoji: "🧀", category: "Main", tag: "TasteAtlas #46",
    why: "Ranked #46 in the world. Georgia's cheese boat: leavened dough cradling molten sulguni and imeruli, crowned with a raw egg yolk and butter to stir in tableside. Tear, swirl, repeat." },
  { name: "Peking Duck", origin: "Beijing, China", emoji: "🦆", category: "Main", tag: "TasteAtlas #55",
    why: "Ranked #55 among the world's best dishes. Air-dried, lacquered with maltose, and roasted until the skin shatters like glass — an imperial recipe perfected over 600 years, wrapped in pancakes with hoisin and scallion." },
  { name: "Massaman Curry", origin: "Thailand", emoji: "🍛", category: "Main", tag: "CNN's most delicious 2017",
    why: "Crowned the most delicious food on the planet in CNN's 2017 reader vote. A Persian-influenced Thai curry of braised beef, potatoes, and peanuts — sweet, sour, and warmly spiced. The dish chefs most often call the world's best curry." },
  { name: "Rendang", origin: "Indonesia", emoji: "🥘", category: "Main", tag: "CNN's #1 dish, twice",
    why: "Topped CNN's reader poll of the world's 50 best foods — twice. Beef braised for hours in coconut milk and a dozen spices until the liquid caramelizes into a dark, intense coating. The Minangkabau say true rendang takes half a day." },
  { name: "Moussaka", origin: "Greece", emoji: "🍆", category: "Main", tag: "Aegean classic",
    why: "Layers of fried eggplant, spiced lamb, and béchamel baked into Greece's national casserole. Created in its modern form by chef Nikolaos Tselementes in the 1920s — peasant ingredients turned into the taste of the Aegean summer." },
  { name: "Feijoada", origin: "Brazil", emoji: "🫘", category: "Main", tag: "Brazil's national dish",
    why: "Brazil's national dish: black beans slow-stewed with pork, served with rice, collard greens, farofa, and orange slices. Born of Afro-Brazilian ingenuity and eaten nationwide on Wednesdays and Saturdays — a whole culture in a clay pot." },
  { name: "Chicken Tikka Masala", origin: "United Kingdom", emoji: "🍗", category: "Main", tag: "Britain's adopted curry",
    why: "Char-grilled chicken in a creamy tomato-fenugreek sauce — invented in Britain by South Asian chefs and once called 'a true British national dish' by a foreign secretary. The curry that built a thousand high streets." },
  { name: "Sinigang", origin: "Philippines", emoji: "🍲", category: "Soup", tag: "TasteAtlas #41",
    why: "Ranked #41 in the world. The Philippines' beloved sour soup — tamarind broth loaded with pork, shrimp, or fish and garden vegetables. Tangy, soulful, and endlessly adaptable; Filipinos call it the taste of home." },
  { name: "Tom Yum Goong", origin: "Thailand", emoji: "🦐", category: "Soup", tag: "Hot-sour icon",
    why: "Lemongrass, galangal, makrut lime, and chili in a clear, electrifying broth crowned with river prawns. The soup that taught the world what 'hot and sour' should mean — Thailand's most famous export after pad thai." },
  { name: "French Onion Soup", origin: "France", emoji: "🧅", category: "Soup", tag: "Bistro classic",
    why: "Onions caramelized to mahogany, deglazed with wine, crowned with a Gruyère-crusted crouton. Parisian bistro canon since the 19th century — peasant thrift transformed into the most comforting bowl in France." },
  { name: "Laksa", origin: "Malaysia", emoji: "🍜", category: "Soup", tag: "Southeast Asian icon",
    why: "A coconut-curry broth humming with shrimp paste and lemongrass, loaded with noodles, prawns, and bean sprouts. Malaysia and Singapore's hawker-centre crown jewel — fiery, creamy, and fiercely debated in both homelands." },
  { name: "Miso Soup", origin: "Japan", emoji: "🍲", category: "Soup", tag: "Daily staple",
    why: "Fermented soybean paste whisked into dashi with tofu, wakame, and scallions — served at nearly every Japanese breakfast. Simple, restorative, and endlessly variable; the quiet backbone of Japanese home cooking." },
  { name: "Borscht", origin: "Ukraine", emoji: "🥣", category: "Soup", tag: "Eastern European classic",
    why: "Beetroot, cabbage, and beef in a sweet-sour crimson broth, crowned with smetana and dill. Ukraine's UNESCO-recognized culinary heritage — a bowl of history that has fueled Eastern Europe for centuries." },
  { name: "Clam Chowder", origin: "New England, USA", emoji: "🦪", category: "Soup", tag: "New England icon",
    why: "Quahog clams, potatoes, and cream in the thick white chowder that launched a thousand bread bowls. New England's 19th-century fisherman's fuel — so beloved that Manhattan's tomato version started a chowder war." },
  { name: "Tom Kha Gai", origin: "Thailand", emoji: "🍲", category: "Soup", tag: "Coconut classic",
    why: "Chicken poached in coconut milk fragrant with galangal, lemongrass, and lime leaf. Creamy, floral, and gently hot — the mellow counterpart to tom yum and Thailand's most elegant soup." },
  { name: "Pad Thai", origin: "Thailand", emoji: "🍜", category: "Street Food", tag: "World-famous noodles",
    why: "Rice noodles wok-tossed in tamarind, fish sauce, and palm sugar with shrimp, tofu, egg, and crushed peanut. A 1930s nation-building dish that became Thailand's global ambassador — sweet, sour, salty, crunchy in every bite." },
  { name: "Banh Mi", origin: "Vietnam", emoji: "🥖", category: "Street Food", tag: "Fusion sandwich",
    why: "A French baguette gone Vietnamese: crackling crust, pickled daikon and carrot, cilantro, pâté, and lemongrass pork. Colonial history you can eat — voted among the world's best sandwiches again and again." },
  { name: "Shawarma", origin: "Lebanon", emoji: "🌯", category: "Street Food", tag: "Middle Eastern icon",
    why: "Marinated meat shaved off a vertical spit, wrapped with garlic toum, pickles, and fries. The Ottoman Empire's gift to street food — the template for döner, tacos al pastor, and half the world's late-night food." },
  { name: "Poutine", origin: "Quebec, Canada", emoji: "🍟", category: "Street Food", tag: "Canadian icon",
    why: "Crisp fries, fresh cheese curds, and hot gravy — invented in 1950s Quebec and now Canada's edible flag. The curds must squeak; the gravy must be hot enough to melt them. Simplicity perfected in the snow." },
  { name: "Currywurst", origin: "Berlin, Germany", emoji: "🌭", category: "Street Food", tag: "Berlin icon",
    why: "Sliced bratwurst drowned in curried ketchup, eaten standing up with a tiny wooden fork. Postwar Berlin's invention — British soldiers' curry powder meets German sausage — now a national obsession with its own museum." },
  { name: "Arepas", origin: "Venezuela", emoji: "🫓", category: "Street Food", tag: "Corn cake staple",
    why: "Grilled cornmeal cakes split and stuffed with shredded beef, black beans, or reina pepiada chicken salad. A pre-Columbian staple turned Venezuelan daily bread — crispy outside, steamy inside, endlessly fillable." },
  { name: "Satay", origin: "Indonesia", emoji: "🍢", category: "Street Food", tag: "Grilled skewer icon",
    why: "Charcoal-grilled skewers of marinated chicken, goat, or beef with sweet-spicy peanut sauce and ketupat rice cakes. Java's night-market perfume — smoke, turmeric, and caramelized peanut in every bite." },
  { name: "Fish and Chips", origin: "England", emoji: "🐟", category: "Street Food", tag: "British institution",
    why: "Beer-battered cod and twice-cooked chips in paper with salt and vinegar — Britain's 19th-century working-class fuel, now a protected cultural icon. Crisp, steaming, and best eaten by the sea." },
  { name: "Samosa", origin: "India", emoji: "🥟", category: "Snack", tag: "Crisp pastry icon",
    why: "A shattering fried pastry around spiced potatoes and peas, served with tamarind and mint chutneys. From Mughal-era courts to Mumbai street corners — the world's most successful triangular food." },
  { name: "Empanada", origin: "Argentina", emoji: "🥟", category: "Snack", tag: "Handheld classic",
    why: "Half-moon pastries crimped by hand — each region has its own repulgue pattern — around beef, onion, and olive. Argentina's portable feast; the fold tells you what's inside, if you know the code." },
  { name: "Gyoza", origin: "Japan", emoji: "🥟", category: "Snack", tag: "Dumpling icon",
    why: "Pan-fried potstickers with lacy crispy skirts, filled with pork, cabbage, and garlic chives. A postwar import from China perfected in Japan's izakayas — the ideal three-bite companion to cold beer." },
  { name: "Arancini", origin: "Sicily, Italy", emoji: "🍘", category: "Snack", tag: "Sicilian icon",
    why: "Risotto balls stuffed with ragù or mozzarella, breaded and fried to gold. Named for little oranges and born in 10th-century Sicily — the island's answer to leftover rice, and nobody's leftovers ever tasted better." },
  { name: "Falafel", origin: "Middle East", emoji: "🧆", category: "Snack", tag: "Chickpea classic",
    why: "Ground chickpeas and herbs fried into herb-green, shattering croquettes, tucked into pita with tahini. Egypt and the Levant's ancient fast food — crisp outside, fluffy inside, vegan before it was a word." },
  { name: "Takoyaki", origin: "Osaka, Japan", emoji: "🐙", category: "Snack", tag: "Osaka icon",
    why: "Batter balls griddled in dimpled pans around octopus, brushed with sauce and mayo, dusted with bonito that dances in the heat. Osaka's street-food theater — molten inside, best eaten scalding." },
  { name: "Tiramisu", origin: "Italy", emoji: "🍰", category: "Dessert", tag: "Dessert classic",
    why: "Espresso-soaked savoiardi layered with mascarpone cream and dusted with cocoa — invented in 1960s Treviso, now the world's most-ordered Italian dessert. 'Pick me up' in every sense." },
  { name: "Crème Brûlée", origin: "France", emoji: "🍮", category: "Dessert", tag: "Dessert classic",
    why: "Silken vanilla custard under a torched sugar crust you crack with a spoon. France's 17th-century tables turned custard into theater — cold cream against hot glass sugar is pure drama." },
  { name: "Baklava", origin: "Turkey", emoji: "🥜", category: "Dessert", tag: "Dessert classic",
    why: "Forty whisper-thin layers of phyllo, crushed pistachio or walnut, and syrup — perfected in Ottoman palace kitchens. Gaziantep's pistachio version has EU protected status. Shattering, sticky, worth the mess." },
  { name: "Churros", origin: "Spain", emoji: "🥖", category: "Dessert", tag: "Dessert classic",
    why: "Ridged fried dough dusted with sugar, dunked in thick drinking chocolate. Madrid's San Ginés has fried them since 1894 — Spain's 2 a.m. answer to every question, now beloved from Mexico City to Manila." },
  { name: "Pavlova", origin: "Australia", emoji: "🍰", category: "Dessert", tag: "Dessert classic",
    why: "Crisp meringue shell, marshmallow center, whipped cream, and passionfruit — named for ballerina Anna Pavlova during her 1920s tour. Australia and New Zealand still feud over its birthplace; everyone agrees on the taste." },
  { name: "Sticky Toffee Pudding", origin: "England", emoji: "🍮", category: "Dessert", tag: "Dessert classic",
    why: "Date sponge drowned in hot toffee sauce with clotted cream — the Lake District's gift to winter. Sticky, dark, and unapologetically rich; Britain's coziest dessert." },
  { name: "Tres Leches Cake", origin: "Mexico", emoji: "🍰", category: "Dessert", tag: "Dessert classic",
    why: "Sponge soaked in evaporated, condensed, and whole milk until impossibly moist, crowned with cream and cinnamon. Latin America's celebration cake — proof that more dairy is always the answer." },
  { name: "Gulab Jamun", origin: "India", emoji: "🍩", category: "Dessert", tag: "Dessert classic",
    why: "Milk-solid dumplings fried low and slow, then soaked in rose-cardamom syrup until they glisten. Served warm at every Indian festival — soft, syrupy, and gone in seconds." },
  { name: "Mango Sticky Rice", origin: "Thailand", emoji: "🥭", category: "Dessert", tag: "Dessert classic",
    why: "Coconut-milk sticky rice with honey mango and a drizzle of salted coconut cream. Thailand's mango season in a bowl — sweet, salty, and creamy in perfect balance." },
  { name: "Panna Cotta", origin: "Italy", emoji: "🍮", category: "Dessert", tag: "Dessert classic",
    why: "Barely-set cream perfumed with vanilla, unmolded with a tremble and sauced with berries. Piedmont's minimalist masterpiece — three ingredients, infinite elegance." },
  { name: "Pastel de Nata", origin: "Portugal", emoji: "🥧", category: "Dessert", tag: "Lisbon icon",
    why: "Blistered custard tarts from Belém's 1837 monastery recipe, dusted with cinnamon. Crisp laminated shell, caramelized custard — Lisbon's edible landmark, best eaten warm with an espresso." },
  { name: "Apfelstrudel", origin: "Austria", emoji: "🍎", category: "Dessert", tag: "Dessert classic",
    why: "Hand-stretched strudel dough wrapped around spiced apples, raisins, and breadcrumbs, served with vanilla sauce. Vienna's coffee-house crown jewel — the dough must be thin enough to read through." },
  { name: "Brigadeiro", origin: "Brazil", emoji: "🍫", category: "Candy", tag: "Candy classic",
    why: "Condensed milk, cocoa, and butter rolled in chocolate sprinkles — Brazil's 1940s party truffle, named for a presidential candidate. Fudgy, tiny, and impossible to eat just one." },
  { name: "Turkish Delight", origin: "Turkey", emoji: "🍬", category: "Candy", tag: "Candy classic",
    why: "Rosewater-scented jelly cubes dusted in powdered sugar — lokum has sweetened Istanbul since the 1700s. The confection that made an empire famous for dessert." },
  { name: "Alfajores", origin: "Argentina", emoji: "🍪", category: "Candy", tag: "Candy classic",
    why: "Two shortbread cookies sandwiched with dulce de leche, often enrobed in chocolate. Argentina's national sweet — kiosks sell dozens of brands, and everyone has a loyalty." },
  { name: "Halva", origin: "Middle East", emoji: "🍯", category: "Candy", tag: "Candy classic",
    why: "Crumbly tahini-and-sugar confection, sometimes studded with pistachio — a 3,000-year-old sweet from the ancient Middle East. Nutty, melt-away, and endlessly giftable." },
  { name: "Full English Breakfast", origin: "England", emoji: "🍳", category: "Breakfast", tag: "Breakfast institution",
    why: "Bacon, sausage, eggs, beans, tomato, mushrooms, black pudding, toast — the fry-up that fueled an empire. Eaten on weekends with strong tea and zero regrets; Britain's most famous plate." },
  { name: "Shakshuka", origin: "Middle East", emoji: "🍳", category: "Breakfast", tag: "Breakfast classic",
    why: "Eggs poached in smoky tomato-pepper sauce, scooped with bread straight from the pan. North African roots, Israeli brunch fame — one pan, infinite comfort." },
  { name: "Congee", origin: "China", emoji: "🍚", category: "Breakfast", tag: "Breakfast staple",
    why: "Rice simmered into silk, topped with century egg, pork floss, or pickles. China's 3,000-year-old morning bowl — gentle, warming, and the first food of every convalescence." },
  { name: "Eggs Benedict", origin: "USA", emoji: "🍳", category: "Breakfast", tag: "Brunch icon",
    why: "Poached eggs and ham on an English muffin under hollandaise — invented at a grand New York hotel in the 1890s. Brunch's founding dish and hollandaise's greatest showcase." },
  { name: "Menemen", origin: "Turkey", emoji: "🍳", category: "Breakfast", tag: "Breakfast classic",
    why: "Eggs scrambled into tomatoes, peppers, and olive oil, eaten with bread from the pan. Turkey's weekend ritual — shakshuka's Anatolian cousin, simpler and just as scooped-up." },
  { name: "Croque Madame", origin: "France", emoji: "🥪", category: "Breakfast", tag: "Bistro breakfast",
    why: "A croque monsieur crowned with a fried egg — ham, Gruyère, and béchamel under a golden lid. Parisian café canon: the madame wears her hat, the monsieur doesn't." },
  { name: "Espresso", origin: "Italy", emoji: "☕", category: "Drink", tag: "Coffee icon",
    why: "A 25-second extraction that built a nation's rhythm — invented in Turin in 1884, perfected in Milan's bar culture. Drunk standing, in three sips, several times a day: Italy's operating system." },
  { name: "Turkish Coffee", origin: "Turkey", emoji: "☕", category: "Drink", tag: "UNESCO coffee culture",
    why: "Powder-fine coffee simmered in a cezve and served unfiltered — the 500-year-old ritual that gave English the word 'coffee.' UNESCO-listed heritage, read in the cup's dregs." },
  { name: "Masala Chai", origin: "India", emoji: "🫖", category: "Drink", tag: "Spiced tea icon",
    why: "Assam tea boiled with milk, ginger, cardamom, and cloves, poured from height by street vendors. India's hundred-million-cup-a-day habit — the subcontinent's heartbeat in a clay kulhad." },
  { name: "Bubble Tea", origin: "Taiwan", emoji: "🧋", category: "Drink", tag: "Global phenomenon",
    why: "Milk tea shaken with chewy tapioca pearls — invented in 1980s Taichung, now a multi-billion-dollar global craze. The drink that made chewing your beverage normal." },
  { name: "Ratatouille", origin: "France", emoji: "🍅", category: "Side", tag: "Provençal classic",
    why: "Provençal vegetables — zucchini, eggplant, peppers, tomato — stewed with herbes de Provence into summer itself. Nice's peasant classic, immortalized by a rat with a dream." },
  { name: "Hummus", origin: "Middle East", emoji: "🫒", category: "Side", tag: "Mezze icon",
    why: "Chickpeas whipped with tahini, lemon, and olive oil into silk. The Levant's centuries-old mezze anchor — argued over by nations, scooped up by everyone." },
  { name: "Ceviche", origin: "Peru", emoji: "🐟", category: "Seafood", tag: "Peruvian icon",
    why: "Day-boat sea bass 'cooked' in lime leche de tigre with red onion, ají, and choclo corn. Peru's ancient technique, now its national dish — the freshest argument for minimal cooking on Earth." },
  { name: "Lobster Roll", origin: "New England, USA", emoji: "🦞", category: "Seafood", tag: "New England icon",
    why: "Sweet Maine lobster in a buttered, toasted split-top bun — Connecticut warm with butter, Maine cold with mayo. Summer in a bun, and the reason lobster shacks have lines around the block." },
  { name: "Gambas al Ajillo", origin: "Spain", emoji: "🦐", category: "Seafood", tag: "Tapas icon",
    why: "Shrimp sizzled in olive oil with sliced garlic and chili, served still bubbling in a clay cazuela. Madrid's tapas-bar essential — the oil, mopped with bread, is half the dish." },
  { name: "Bouillabaisse", origin: "Marseille, France", emoji: "🍲", category: "Seafood", tag: "Marseille classic",
    why: "Marseille's saffron fisherman's stew — rockfish, rouille, and croutons. Born from unsold catch, elevated to legend; true bouillabaisse follows a charter written in 1980." },
];

const WORST = [
  { name: "Pizza Vulkanen", origin: "Piteå, Sweden", emoji: "🌋", category: "Main", tag: "TasteAtlas worst #1 · 1.6/5",
    why: "The lowest-rated food on Earth: 1.6 out of 5 from nearly half a million legitimate TasteAtlas ratings. A ring-shaped pizza stuffed with cheese, ham, salami, bacon, and beef tenderloin, with french fries and Béarnaise salad erupting from the center. Maximum chaos, minimum restraint — voters found it grotesque, not fun." },
  { name: "Svið", origin: "Iceland", emoji: "🐑", category: "Main", tag: "TasteAtlas worst #2 · 1.7/5",
    why: "A singed, halved sheep's head — cooked with the face staring back at you. Born from an era when no part of the animal could be wasted, served at the midwinter Þorrablót festival with mashed turnips. Locals insist it is tasty; the rest of the world could not get past looking dinner in the eye." },
  { name: "Thorramatur", origin: "Iceland", emoji: "🦈", category: "Main", tag: "TasteAtlas worst #3 · 1.8/5",
    why: "A full buffet platter of Iceland's most challenging foods — fermented shark, blood sausages, seared lamb head, smoked lamb — eaten during the month of Þorri. Less a dish than a survival gauntlet of preservation-era flavors. Voters punished it into the #3 worst spot on the planet." },
  { name: "Truchas a la Navarra", origin: "Navarre, Spain", emoji: "🐟", category: "Seafood", tag: "TasteAtlas worst #4",
    why: "Trout stuffed with cured ham sounds reasonable until the execution: river fish wrapped around salty pork creates a muddy, confused flavor satisfying neither craving. TasteAtlas voters ranked it the 4th worst food in the world — proof that two good things do not always make one." },
  { name: "Blodpalt", origin: "Norrland, Sweden", emoji: "🩸", category: "Main", tag: "TasteAtlas worst #5",
    why: "Dumplings of reindeer blood, barley flour, and diced pork, boiled and served with lingonberries. A historic survival food of the far north, but the metallic, iron-heavy flavor and near-black appearance make it a hard sell for anyone who did not grow up with it." },
  { name: "Kugel Yerushalmi", origin: "Jerusalem, Israel", emoji: "🍝", category: "Side", tag: "TasteAtlas worst #6",
    why: "A baked noodle pudding that is simultaneously sweet (caramelized sugar) and aggressively peppery — a combination most palates read as a mistake. Beloved in Jerusalem's ultra-Orthodox community as Sabbath food, but outsiders rate it among the most confusing things they have ever tasted." },
  { name: "Blodplättar", origin: "Sweden", emoji: "🥞", category: "Breakfast", tag: "TasteAtlas worst #7",
    why: "Pancakes made with pig or reindeer blood, onions, and spices, fried and served with lingonberry jam. Once everyday food across the Nordics, the iron-rich metallic taste now reads as shocking to modern eaters. Blood dishes sit near the very bottom of the rankings year after year." },
  { name: "Milcao", origin: "Chiloé, Chile", emoji: "🥔", category: "Side", tag: "TasteAtlas worst #8",
    why: "A dense potato bread from Chile's Chiloé archipelago — grated raw and cooked potatoes fried into heavy cakes. Filling peasant fuel, but its gluey, leaden texture and plainness leave first-timers wondering what the point was." },
  { name: "Hon Mhai (Fried Silkworms)", origin: "Thailand", emoji: "🐛", category: "Snack", tag: "TasteAtlas worst #9",
    why: "Silkworm pupae deep-fried with salt and pepper — a protein-rich Isaan snack. The problem is the pop: a soft, pulpy interior that bursts in the mouth. Even adventurous eaters who happily crunch crickets often draw the line at the texture of these." },
  { name: "Chapalele", origin: "Chiloé, Chile", emoji: "🍞", category: "Side", tag: "TasteAtlas worst #10",
    why: "Another Chiloé staple: boiled dumplings of potato and wheat flour, sometimes sweetened. Soft, pale, and starchy to the point of vanishing — voters found it the definition of forgettable, a dish that tastes like the absence of flavor." },
  { name: "Jellied Eels", origin: "London, England", emoji: "🐍", category: "Seafood", tag: "TasteAtlas worst #11",
    why: "Chopped eels boiled in spiced stock that sets into a natural jelly — working-class London street food since the 1700s. The flavor is mild; the texture of cold, wobbling fish jelly is what ends careers. Even most Londoners under 50 have never willingly eaten it." },
  { name: "Aginares Salata", origin: "Crete, Greece", emoji: "🌿", category: "Side", tag: "TasteAtlas worst #12",
    why: "A cold artichoke salad that voters found bland, mushy, and relentlessly fibrous. Crete's cuisine is world-famous, which made this entry sting — even great food cultures produce a dish the world collectively shrugs at." },
  { name: "Ambuyat", origin: "Brunei", emoji: "🫠", category: "Side", tag: "TasteAtlas worst #13",
    why: "Sago palm starch stirred with boiling water into a translucent, glue-like blob, twirled onto a bamboo fork. It has almost no flavor of its own — the entire experience is texture, and the texture is wallpaper paste. Brunei's national dish is a dare disguised as dinner." },
  { name: "Nervetti", origin: "Milan, Italy", emoji: "🦴", category: "Side", tag: "TasteAtlas worst #14",
    why: "Calf's foot tendons, boiled, sliced, and served cold as a salad with beans and onions. Gelatinous, wobbly, and unapologetically odd — even in Italy, land of fearless eating, nervetti is a niche passion. Milan's contribution to the world's worst list." },
  { name: "Ramen Burger", origin: "New York City, USA", emoji: "🍔", category: "Street Food", tag: "TasteAtlas worst #15",
    why: "A 2013 Brooklyn invention: a beef patty sandwiched between two 'buns' of fried ramen noodles. The gimmick broke the internet for a week; the reality is a greasy, falling-apart mess worse than both a burger and a bowl of ramen. Novelty is not flavor." },
  { name: "Żymlok", origin: "Silesia, Poland", emoji: "🌭", category: "Main", tag: "TasteAtlas worst #16",
    why: "A Silesian blood sausage of pork blood, groats, and offal, dense and dark as coal. Poland's cuisine ranks among the world's best overall — which makes its blood sausage's place at #16 on the worst list a reminder that every food culture has its divisive corner." },
  { name: "Kichel", origin: "Israel", emoji: "🍪", category: "Snack", tag: "TasteAtlas worst #17",
    why: "A sweet, dry, bow-tie-shaped cracker-cookie from Ashkenazi baking tradition. Inoffensive is the problem: voters found it stale-tasting and pointless, the rare baked good that made a worst-foods list purely by being aggressively forgettable." },
  { name: "Tortilla Paisana", origin: "Spain", emoji: "🍳", category: "Breakfast", tag: "TasteAtlas worst #18",
    why: "Spain's beloved tortilla formula gone wrong: a peasant omelette overloaded with vegetables until it turns soggy and muddled. Next to the perfect tortilla española, this version tastes like a cautionary tale — and voters ranked it #18 worst in the world." },
  { name: "Heusuppe", origin: "Switzerland", emoji: "🌾", category: "Soup", tag: "TasteAtlas worst #19",
    why: "Hay soup. Literally broth infused with mountain hay, a novelty from the Swiss Alps. It tastes the way a barn smells — which is exactly the problem. Even adventurous diners filed it under 'tried once,' landing it at #19 worst on Earth." },
  { name: "Kaeng Tai Pla", origin: "Southern Thailand", emoji: "🐟", category: "Soup", tag: "TasteAtlas worst #20",
    why: "A dense curry built on fermented fish entrails blended with fierce chili paste, galangal, and shrimp paste. Southern Thailand's most pungent dish was once crowned the single worst dish in the world by TasteAtlas. Fermentation fans call it complex; everyone else calls it a biohazard." },
  { name: "Surströmming", origin: "Sweden", emoji: "🐟", category: "Seafood", tag: "Smell hazard",
    why: "Fermented Baltic herring canned while still fermenting, so tins bulge and spray on opening — always opened outdoors, by law of common sense. Studies rank it among the smelliest foods on the planet. The taste is milder than the smell, but nobody gets past the smell." },
  { name: "Hákarl", origin: "Iceland", emoji: "🦈", category: "Snack", tag: "Ammonia cubes",
    why: "Greenland shark is poisonous when fresh, so Icelanders ferment it for months and hang it to dry — producing cubes that reek of ammonia. Anthony Bourdain called it the single worst thing he ever ate. A Viking-era food-safety solution that never got repealed." },
  { name: "Balut", origin: "Philippines", emoji: "🥚", category: "Street Food", tag: "Fear factor",
    why: "A fertilized duck egg, boiled and eaten whole from the shell — veins, beak, and all. Beloved in the Philippines as beer food and a stamina snack, but the texture surprise ruins most first-timers. The dish that launched a thousand reality-TV dares." },
  { name: "Casu Marzu", origin: "Sardinia, Italy", emoji: "🧀", category: "Side", tag: "Legally banned",
    why: "Pecorino aged until it hosts live cheese-fly larvae — yes, live — which digest the fats into a soft, pungent paste. Banned by the EU, sold on Sardinia's black market. The larvae can jump 15 cm when disturbed. Cheese was not supposed to move." },
  { name: "Fesikh", origin: "Egypt", emoji: "🐟", category: "Seafood", tag: "Salted mullet",
    why: "Grey mullet fermented in salt for weeks, eaten whole at Egypt's spring festival Sham El Nessim — a 5,000-year-old tradition. When prepared badly it can harbor botulism, so the government issues annual warnings. Ancient, risky, and intensely fishy." },
  { name: "Smalahove", origin: "Norway", emoji: "🐑", category: "Main", tag: "Sheep's head",
    why: "Norway's answer to svið: a singed sheep's head, split and served with mashed rutabaga — traditionally eaten with the eyes and ears first. A pre-Christmas delicacy in western Norway that most of the world files under 'absolutely not.'" },
  { name: "Calskrove", origin: "Skellefteå, Sweden", emoji: "🍕", category: "Street Food", tag: "Burger calzone",
    why: "A calzone stuffed with french fries and entire hamburgers — buns and all — invented at a Swedish pizzeria. It sounds like an American fever dream but it is Swedish, and it has repeatedly landed on worst-food lists. Two fast foods entered; no dignity left." },
  { name: "Luther Burger", origin: "Georgia, USA", emoji: "🍩", category: "Street Food", tag: "Donut burger",
    why: "A bacon cheeseburger served on a glazed donut instead of a bun — allegedly named for Luther Vandross. Sticky, collapsing, and a sugar bomb on top of a salt bomb. The American South's most chaotic contribution to the worst-foods conversation." },
  { name: "Pani ca Meusa", origin: "Palermo, Italy", emoji: "🥪", category: "Street Food", tag: "Spleen sandwich",
    why: "A soft roll stuffed with sliced veal spleen and lung, boiled then fried in lard, splashed with lemon. Palermo's beloved street food has fed workers for centuries — and horrified everyone else. Offal loyalty at its most extreme." },
  { name: "Frog Eye Salad", origin: "Utah, USA", emoji: "🐸", category: "Dessert", tag: "TasteAtlas worst #22 (2025)",
    why: "Acini di pepe pasta — the tiny 'frog eye' pearls — folded into whipped topping with canned fruit and marshmallows, served as a 'salad' at Mormon potlucks. Pasta for dessert is where many draw the line. Ranked #22 worst in the world in 2025." },
  { name: "Lutefisk", origin: "Norway", emoji: "🐟", category: "Main", tag: "Gelatinous cod",
    why: "Cod soaked in lye until it turns to quivering jelly, then baked — a Norwegian-American Christmas tradition born of preservation necessity. The texture is the verdict: voters describe it as fish-flavored gelatin, and not fondly." },
  { name: "Haggis", origin: "Scotland", emoji: "🐑", category: "Main", tag: "Divisive icon",
    why: "Sheep's pluck — heart, liver, lungs — minced with oats and spices, boiled in the stomach. Scots revere it on Burns Night; outsiders hear the ingredient list and stop listening. Honestly delicious to many, unthinkable to more." },
  { name: "Andouillette", origin: "France", emoji: "🌭", category: "Main", tag: "Tripe sausage",
    why: "A sausage of pork intestines and tripe with a famously barnyard aroma — France even grades them through a dedicated association. Lyon's bouchons love it; everyone else smells it from the doorway." },
  { name: "Tuna Casserole", origin: "USA", emoji: "🥘", category: "Main", tag: "TasteAtlas #73 (2025)",
    why: "Ranked #73 worst in the world in 2025. Canned tuna, canned soup, and egg noodles baked into a beige slab — midcentury American convenience cooking at its most joyless. Nostalgia is its only seasoning." },
  { name: "Chicken à la King", origin: "USA", emoji: "🍗", category: "Main", tag: "TasteAtlas #82 (2025)",
    why: "Ranked #82 worst in 2025. Diced chicken in a floury sherry-cream sauce over toast — a 1900s hotel dish that became a freezer-aisle ghost. Creamy, pale, and forgotten for good reason." },
  { name: "Chicken Riggies", origin: "Utica, USA", emoji: "🍝", category: "Main", tag: "TasteAtlas #86 (2025)",
    why: "Ranked #86 worst in 2025. Utica, New York's spicy chicken-and-rigatoni in creamy tomato sauce — locals defend it fiercely, but voters found it heavy and muddled. Regional pride vs. global palate." },
  { name: "Cuy (Guinea Pig)", origin: "Peru", emoji: "🐹", category: "Main", tag: "Divisive delicacy",
    why: "Whole roasted guinea pig, served splayed like a tiny banquet — an Andean protein for 5,000 years, even painted into a Cusco Last Supper. Pet in the West, feast in the Andes; the cultural whiplash is the dish." },
  { name: "Chitterlings", origin: "USA", emoji: "🐖", category: "Main", tag: "Divisive soul food",
    why: "Slow-simmered pig intestines, cleaned for hours before cooking — a soul-food staple with deep roots in survival and celebration. The days-long cleaning smell alone has ended friendships." },
  { name: "Muktuk", origin: "Arctic", emoji: "🐋", category: "Main", tag: "Whale skin delicacy",
    why: "Raw bowhead whale skin and blubber, chewed like gum by Inuit communities — rich in vitamin C where no fruit grows. Nutritionally brilliant, texturally challenging, and debated far from the Arctic." },
  { name: "Canned Whole Chicken", origin: "USA", emoji: "🥫", category: "Main", tag: "Infamous pantry item",
    why: "A whole chicken, canned in jelly, that slides out in one wobbling piece — a real product that became an internet horror icon. Technically shelf-stable poultry; spiritually a cry for help." },
  { name: "Menudo", origin: "Mexico", emoji: "🍲", category: "Soup", tag: "Tripe soup",
    why: "Beef tripe and hominy in red chili broth — Mexico's legendary hangover cure, simmered for hours. Devotees swear by it at dawn; the honeycomb tripe texture converts almost no one else." },
  { name: "Bird's Nest Soup", origin: "China", emoji: "🪹", category: "Soup", tag: "Luxury divisive",
    why: "Soup of swiftlet saliva nests dissolved into a gelatinous broth — a Qing-dynasty luxury prized for supposed health benefits. At hundreds of dollars a bowl, it's the world's priciest bowl of texture complaints." },
  { name: "Czernina", origin: "Poland", emoji: "🩸", category: "Soup", tag: "Duck blood soup",
    why: "Duck blood whisked into a sweet-sour broth with dried fruit — once served to rejected suitors in Polish courtship ritual. The symbolism is clearer than the flavor, which voters found deeply unsettling." },
  { name: "Żurek", origin: "Poland", emoji: "🍞", category: "Soup", tag: "Sour rye soup",
    why: "Fermented rye starter gives this Easter soup its signature sour tang, loaded with sausage and egg. Poles love it; outsiders taste liquid sourdough with meat and politely decline seconds." },
  { name: "Okroshka", origin: "Russia", emoji: "🥣", category: "Soup", tag: "Cold kvass soup",
    why: "Chopped vegetables, egg, and sausage served ice-cold in kvass — fermented bread soda. Russia's summer cooler reads to newcomers as salad drowned in fizzy bread drink. Refreshing or wrong, no middle ground." },
  { name: "Turtle Soup", origin: "USA", emoji: "🐢", category: "Soup", tag: "Old luxury",
    why: "Snapping turtle simmered with sherry into a rich, gamey soup — once the pinnacle of American fine dining, now rare and ethically fraught. A delicacy from an era with different rules." },
  { name: "Stinky Tofu", origin: "Taiwan", emoji: "🫘", category: "Street Food", tag: "Infamous aroma",
    why: "Fermented tofu deep-fried until crisp — the smell, from its brine, announces it a block away. Fans call the flavor mild and savory; everyone else calls the fire department. Banned from some hotels, beloved in night markets." },
  { name: "Lampredotto", origin: "Florence, Italy", emoji: "🥪", category: "Street Food", tag: "Tripe sandwich",
    why: "Cow's fourth stomach simmered in broth, chopped, and stuffed into a roll with salsa verde. Florence's working-class lunch for 500 years — tender for fans, a biology lesson for everyone else." },
  { name: "Chapulines", origin: "Oaxaca, Mexico", emoji: "🦗", category: "Street Food", tag: "Grasshopper snack",
    why: "Toasted grasshoppers with lime, salt, and chili — Oaxacan protein for millennia, crunchy and citrusy. Nutritionally superb; psychologically a bridge too far for most visitors." },
  { name: "Fried Tarantula", origin: "Cambodia", emoji: "🕷️", category: "Street Food", tag: "Shock snack",
    why: "Whole tarantulas fried with garlic in Skuon, Cambodia — born of Khmer Rouge-era hunger, now a dare food. Crispy legs, soft abdomen; the crunch is the easy part." },
  { name: "Deep-Fried Mars Bar", origin: "Scotland", emoji: "🍫", category: "Street Food", tag: "Chip-shop legend",
    why: "A Mars bar battered and deep-fried in a Stonehaven chip shop — Scotland's infamous contribution to excess. Gooey, scalding, and over a thousand calories of 'why'; the world cites it as proof of chip-shop anarchy." },
  { name: "Mopane Worms", origin: "Zimbabwe", emoji: "🐛", category: "Street Food", tag: "Bush protein",
    why: "Harvested mopane caterpillars, dried and fried with tomato and onion — a protein-rich staple across southern Africa. Crunchy and nutritious; the name alone ends most conversations." },
  { name: "Escargot", origin: "France", emoji: "🐌", category: "Street Food", tag: "Garlic snails",
    why: "Burgundy snails baked in garlic-herb butter, extracted with tiny forks — sold at markets as well as bistros. A Roman delicacy turned French cliché: buttery and delicious to fans, a garden pest on a plate to everyone else." },
  { name: "Witchetty Grub", origin: "Australia", emoji: "🐛", category: "Street Food", tag: "Bush tucker",
    why: "Wood-eating moth larvae eaten raw or roasted by Aboriginal Australians for millennia — said to taste like almond. The ultimate bush-tucker dare on every outback tourist itinerary." },
  { name: "Century Egg", origin: "China", emoji: "🥚", category: "Snack", tag: "Divisive delicacy",
    why: "Duck eggs preserved in clay and ash until the white turns amber jelly and the yolk creamy green-black. A thousand years of Chinese technique; newcomers see a rotten egg and cannot be convinced otherwise." },
  { name: "Durian", origin: "Southeast Asia", emoji: "🍈", category: "Snack", tag: "King of fruits?",
    why: "The world's most divisive fruit — custardy, almond-like flesh wrapped in a smell that gets it banned from hotels and subways. Fans pay fortunes for Musang King; haters smell gym socks. There is no middle." },
  { name: "Rocky Mountain Oysters", origin: "USA", emoji: "🐂", category: "Snack", tag: "Not oysters",
    why: "Deep-fried bull testicles — the American West's infamous bar snack, served with cocktail sauce and bravado. The name is a lie agreed upon by an entire region." },
  { name: "Escamoles", origin: "Mexico", emoji: "🐜", category: "Snack", tag: "Ant larvae",
    why: "Ant larvae sautéed in butter with epazote — 'Mexican caviar' since Aztec times, nutty and delicate. The flavor is lovely; the knowledge of what you're eating is the entire battle." },
  { name: "Pickled Pigs' Feet", origin: "USA", emoji: "🐖", category: "Snack", tag: "Bar-jar classic",
    why: "Trotters brined in vinegar in giant bar jars across the American South — gelatinous, tangy, and unapologetic. A snack that stares back from the shelf." },
  { name: "Chocolate-Covered Bacon", origin: "USA", emoji: "🥓", category: "Snack", tag: "TasteAtlas #76 (2025)",
    why: "Ranked #76 worst in the world in 2025. State-fair logic taken to its end: smoky bacon dipped in chocolate. Sweet, salty, and wrong in a way voters couldn't forgive." },
  { name: "Deep-Fried Butter", origin: "USA", emoji: "🧈", category: "Snack", tag: "Fairground excess",
    why: "Frozen butter battered and deep-fried at American state fairs — a dare food that won. It tastes exactly like you'd fear: hot, greasy butter. The concept is the crime." },
  { name: "Kool-Aid Pickles", origin: "USA", emoji: "🥒", category: "Snack", tag: "Southern oddity",
    why: "Dill pickles soaked in cherry Kool-Aid until neon red and candy-sweet — a Mississippi Delta gas-station staple. Sour, sweet, and radioactive-looking; beloved locally, baffling everywhere else." },
  { name: "Fruitcake", origin: "USA", emoji: "🍰", category: "Dessert", tag: "Holiday joke",
    why: "Dense, boozy, candied-fruit-studded cake allegedly regifted for decades — Johnny Carson joked there was only one fruitcake, passed around the world. The dessert that became a punchline." },
  { name: "Ambrosia Salad", origin: "USA", emoji: "🥗", category: "Dessert", tag: "Potluck divisive",
    why: "Canned mandarin, marshmallow, coconut, and whipped topping — the 1960s potluck 'salad' that is unambiguously dessert. Creamy, sweet, and texturally confusing to the uninitiated." },
  { name: "Tavuk Göğsü", origin: "Turkey", emoji: "🍮", category: "Dessert", tag: "Chicken pudding",
    why: "A milk pudding thickened with shredded chicken breast — an Ottoman palace dessert with a texture like no other. Delicate and milky to fans; the ingredient list stops everyone else cold." },
  { name: "Christmas Pudding", origin: "England", emoji: "🎄", category: "Dessert", tag: "Festive divisive",
    why: "A cannonball of suet, dried fruit, and brandy, steamed for hours and set alight — Britain's centuries-old Christmas centerpiece. Dense, dark, and an acquired taste even among the British." },
  { name: "Mincemeat Pie", origin: "England", emoji: "🥧", category: "Dessert", tag: "Holiday divisive",
    why: "Small pies of spiced dried fruit (once actual minced meat) eaten every Christmas in Britain. Sweet, boozy, and medieval — visitors especially tend to approach with suspicion." },
  { name: "Jell-O Salad", origin: "USA", emoji: "🍮", category: "Dessert", tag: "Midcentury oddity",
    why: "Lime gelatin suspended with cottage cheese, fruit, or even shredded carrot — the 1950s American 'salad' that wobbles between courses. A dessert wearing a salad's name tag." },
  { name: "Salmiakki", origin: "Finland", emoji: "🍬", category: "Candy", tag: "Salty licorice",
    why: "Ammonium-chloride salty licorice — Finland's national candy and a rite of passage. Outsiders taste cleaning product; Finns taste childhood. The most polarizing candy on Earth." },
  { name: "Candy Corn", origin: "USA", emoji: "🌽", category: "Candy", tag: "Halloween divisive",
    why: "Tri-color waxy kernels of pure sugar, unchanged since the 1880s — America's most argued-about Halloween candy. Loved nostalgically, described by detractors as tasting like candles." },
  { name: "Black Licorice", origin: "Europe", emoji: "🍬", category: "Candy", tag: "Love-or-hate",
    why: "Anise-flavored chews that split humanity in two — no other candy inspires such pure devotion and such pure revulsion. Scandinavia and the Netherlands built entire candy aisles on it." },
  { name: "Circus Peanuts", origin: "USA", emoji: "🥜", category: "Candy", tag: "Foam oddity",
    why: "Banana-flavored marshmallow foam shaped like peanuts — a 19th-century American candy that tastes like neither. Spongy, orange, and stubbornly still manufactured." },
  { name: "Natto", origin: "Japan", emoji: "🫘", category: "Breakfast", tag: "Stringy divisive",
    why: "Fermented soybeans in sticky, stringy strands over rice — Japan's pungent breakfast staple, rich in vitamin K2. The ammonia-adjacent aroma and spiderweb texture defeat nearly every first-timer." },
  { name: "Vegemite", origin: "Australia", emoji: "🫙", category: "Breakfast", tag: "Misused icon",
    why: "Concentrated yeast-extract spread — on buttered toast in a whisper-thin layer it's umami heaven; by the spoonful it's a salt bomb of despair. Tourists always choose wrong." },
  { name: "Marmite", origin: "England", emoji: "🫙", category: "Breakfast", tag: "Love it or hate it",
    why: "Britain's yeast-extract spread, marketed for decades on pure divisiveness: 'Love it or hate it.' Dark, intense, and yeasty — the rare food whose ad campaign is a warning label." },
  { name: "Black Pudding", origin: "England", emoji: "🩸", category: "Breakfast", tag: "Blood sausage",
    why: "Pig's blood, oats, and suet in a sliceable sausage — the full English's most controversial soldier. Iron-rich and peppery to fans; the concept alone ends the conversation for others." },
  { name: "Scrapple", origin: "Pennsylvania, USA", emoji: "🥓", category: "Breakfast", tag: "Pennsylvania divisive",
    why: "Pennsylvania Dutch loaf of pork scraps and cornmeal, sliced and fried crisp. Waste-not genius to locals, 'everything but the oink' to everyone else — beloved and mocked in equal measure." },
  { name: "Kippers", origin: "England", emoji: "🐟", category: "Breakfast", tag: "Smoked herring",
    why: "Cold-smoked herrings served whole for breakfast — a Victorian staple that perfumes the entire house. Buttery and rich to devotees; the smell alone has strong opinions." },
  { name: "Kumis", origin: "Central Asia", emoji: "🥛", category: "Drink", tag: "Fermented mare's milk",
    why: "Mare's milk fermented into a lightly fizzy, sour, mildly alcoholic drink — the steppe's 2,000-year-old staple. Refreshing to nomads; sour horse milk to everyone else." },
  { name: "Moxie", origin: "USA", emoji: "🥤", category: "Drink", tag: "Divisive soda",
    why: "America's oldest soft drink, flavored with bitter gentian root — New Englanders pledge allegiance while outsiders taste medicine. Its slogan might as well be 'acquired taste.'" },
  { name: "Fernet Branca", origin: "Italy", emoji: "🍸", category: "Drink", tag: "Bitter liqueur",
    why: "A 27-herb amaro so bitter it's a bartender's handshake and an Argentine obsession (with cola). Medicinal, intense, and proudly unlovable — the digestif that divides rooms." },
  { name: "Malört", origin: "Chicago, USA", emoji: "🍸", category: "Drink", tag: "Chicago's punishment",
    why: "Jeppson's Malört — wormwood liqueur so bitter Chicago treats it as a hazing ritual. Tasting notes include grapefruit rind, gasoline, and regret. Famously awful, proudly local." },
  { name: "Aspic", origin: "Europe", emoji: "🍖", category: "Side", tag: "Meat jelly",
    why: "Savory gelatin molded around meat, eggs, and vegetables — 1950s dinner-party glamour, now a texture nightmare. Cold, wobbling meat jelly is a hard sell in any century." },
  { name: "Salo", origin: "Ukraine", emoji: "🥓", category: "Side", tag: "Cured pork fat",
    why: "Salt-cured pork back fat eaten raw on rye with garlic — Ukraine's beloved national snack. Pure, silky fat as a delicacy: transcendent to fans, a cardiologist's warning to others." },
  { name: "Gefilte Fish", origin: "Ashkenazi", emoji: "🐟", category: "Side", tag: "Divisive classic",
    why: "Ground whitefish quenelles poached and served cold in jellied broth — the Ashkenazi Sabbath staple. Grandmothers weep with nostalgia; newcomers see gray fish ovals in jelly." },
  { name: "Head Cheese", origin: "Europe", emoji: "🧀", category: "Side", tag: "Not cheese",
    why: "A terrine of pork head meat set in its own gelatin — no cheese involved, despite the name. Old-world charcuterie brilliance to some; a face in aspic to everyone else." },
  { name: "Overcooked Brussels Sprouts", origin: "Global", emoji: "🥬", category: "Side", tag: "Childhood trauma",
    why: "Boiled into sulfurous gray mush, they scarred a generation — the vegetable voted most hated for decades. Roasted crisp they're innocent; the boiling was the crime." },
  { name: "Mushy Peas", origin: "England", emoji: "🫛", category: "Side", tag: "Chip-shop divisive",
    why: "Marrowfat peas stewed to a lurid green mush — the mandatory companion to fish and chips up north. Comforting to Britons, suspiciously baby-food-like to visitors." },
  { name: "Pickled Herring", origin: "Scandinavia", emoji: "🐟", category: "Side", tag: "Vinegar fish",
    why: "Herring cured in vinegar with onion and spices — Scandinavia's everyday staple, from Swedish midsummer to Dutch street carts. Cold, sour, and fishy: a trinity that divides the world." },
  { name: "Creamed Chipped Beef", origin: "USA", emoji: "🥩", category: "Side", tag: "SOS",
    why: "Dried beef in peppery white gravy on toast — U.S. military 'SOS' fed generations of soldiers. Creamy, salty comfort to veterans; everyone else asks what the S stands for." },
  { name: "Sannakji", origin: "Korea", emoji: "🐙", category: "Seafood", tag: "Live octopus",
    why: "Freshly chopped octopus served still writhing, with sesame oil — the tentacles grip the chopsticks, and occasionally the throat. Seoul's ultimate dare dish; the movement is the entire point, and the entire problem." },
  { name: "Shirako", origin: "Japan", emoji: "🍣", category: "Seafood", tag: "Fish milt",
    why: "Cod or pufferfish milt — soft, creamy sacs served raw or tempura'd in winter. Prized as a seasonal delicacy in Japan; the translation ('milt') ends most Western interest instantly." },
  { name: "Ankimo", origin: "Japan", emoji: "🐟", category: "Seafood", tag: "Monkfish liver",
    why: "Monkfish liver steamed with sake into a pâté Japan calls 'foie gras of the sea.' Silky and rich to devotees; the concept of fish liver divides even adventurous eaters." },
  { name: "Geoduck", origin: "Pacific Northwest", emoji: "🦪", category: "Seafood", tag: "Alien clam",
    why: "A giant burrowing clam with a startling siphon — sweet, crunchy, and prized in Chinese banquets. The flavor is pristine; the appearance is a meme." },
  { name: "Jellyfish Salad", origin: "China", emoji: "🪼", category: "Seafood", tag: "Crunchy divisive",
    why: "Salted jellyfish shredded into a cold sesame-oil salad — crunchy, not slimy, and a Lunar New Year staple. The texture is like nothing else, which is exactly the problem for newcomers." },
  { name: "Whelks", origin: "England", emoji: "🐚", category: "Seafood", tag: "Chewy snails",
    why: "Boiled sea snails with vinegar from British seaside stalls — chewy, briny, and eaten with a pin. A Victorian beach tradition that tastes like rubber bands to the unconverted." },
  { name: "Percebes", origin: "Galicia, Spain", emoji: "🦀", category: "Seafood", tag: "Alien delicacy",
    why: "Goose barnacles pried from wave-battered Galician rocks — among the world's priciest seafood, tasting of pure ocean. They look like dinosaur toes: thrilling and horrifying at once." },
  { name: "Sea Cucumber", origin: "China", emoji: "🥒", category: "Seafood", tag: "Texture challenge",
    why: "The humble sea slug braised into a gelatinous luxury at Chinese banquets — prized for texture, not flavor. Slippery, mild, and expensive: everything about it confuses first-timers." },
  { name: "Bagoong", origin: "Philippines", emoji: "🦐", category: "Seafood", tag: "Fermented shrimp paste",
    why: "Shrimp fermented into a pungent purple paste — the flavor backbone of Filipino cooking, from kare-kare to green mangoes. Indispensable in the cuisine; the smell clears rooms." },
  { name: "Dried Squid", origin: "East Asia", emoji: "🦑", category: "Seafood", tag: "Chewy divisive",
    why: "Whole squid dried into leathery sheets, torn and chewed as a beer snack across East Asia. Sweet, smoky, and jaw-exercising — the aroma alone has started airplane incidents." },
];

const CATEGORIES = ["Main", "Soup", "Street Food", "Snack", "Dessert", "Candy", "Breakfast", "Drink", "Side", "Seafood"];
const activeCat = { best: "All", worst: "All" };

function medal(i) {
  return i === 0 ? "🥇" : i === 1 ? "🥈" : i === 2 ? "🥉" : `#${i + 1}`;
}

function buildChips(kind) {
  const wrap = document.getElementById(kind + "Chips");
  ["All", ...CATEGORIES].forEach(c => {
    const b = document.createElement("button");
    b.className = "chip" + (c === "All" ? " active" : "");
    b.textContent = c;
    b.addEventListener("click", () => {
      activeCat[kind] = c;
      wrap.querySelectorAll(".chip").forEach(x => x.classList.remove("active"));
      b.classList.add("active");
      renderAll();
    });
    wrap.appendChild(b);
  });
}

function render(list, gridId, kind, query) {
  const grid = document.getElementById(gridId);
  grid.innerHTML = "";
  const q = (query || "").toLowerCase().trim();
  const cat = activeCat[kind];
  const filtering = cat !== "All" || q;
  let shown = 0;
  list.forEach((f, i) => {
    if (cat !== "All" && f.category !== cat) return;
    if (q && !(f.name + " " + f.origin + " " + f.why + " " + (f.category || "")).toLowerCase().includes(q)) return;
    shown++;
    const card = document.createElement("article");
    card.className = `card ${kind}` + (!filtering && i < 3 ? " top3" : "");
    card.innerHTML = `
      <div class="rank">${medal(i)}</div>
      <div class="emoji">${f.emoji}</div>
      <h3>${f.name}</h3>
      <div class="origin">${f.origin}</div>
      <div class="catline">${f.category || ""}</div>
      <div class="why"><strong>Why it ranks here:</strong> ${f.why}</div>
      <span class="tag">${f.tag}</span>`;
    grid.appendChild(card);
  });
  const empty = document.getElementById(kind + "Empty");
  if (empty) empty.style.display = shown ? "none" : "block";
}

function renderAll() {
  const q = document.getElementById("search").value;
  render(BEST, "bestGrid", "best", q);
  render(WORST, "worstGrid", "worst", q);
}

buildChips("best");
buildChips("worst");
renderAll();

document.getElementById("search").addEventListener("input", renderAll);

document.querySelectorAll(".tab").forEach(tab => {
  tab.addEventListener("click", () => {
    document.querySelectorAll(".tab").forEach(t => t.classList.remove("active"));
    document.querySelectorAll(".board").forEach(b => b.classList.remove("active"));
    tab.classList.add("active");
    document.getElementById(tab.dataset.tab).classList.add("active");
    window.scrollTo({ top: 0, behavior: "smooth" });
  });
});
